### PR TITLE
Address issue #9

### PR DESCRIPTION
**Pull request by PirosB3**
Addresses https://github.com/mzdaniel/pybay_front_end/issues/9

### CODE REVIEW

**Comment by mzdaniel** [comment]
Fancy!  This is great Daniel.
Maybe we can have the actual date in a more accessible and intuitive place (settings.py or a more project specific one)? 
Also this PR is now blocked by your previous gh-12

**Comment by PirosB3** [comment]
Great idea! will make changes

**Comment by mzdaniel** [comment]
Fantastic.  Lets squash and get rid of those pesky trailing whitespaces for merge and publish.

**Comment by PirosB3** [comment]
Done, added a new PR for that

**Pull request closed without merging**
